---
matrix_room_address: "!UXrSFkkJoppiEZEfgC:matrix.org"

# ssh hardening
network_ipv6_enable: true
ssh_allow_agent_forwarding: true
ssh_permit_tunnel: true
ssh_allow_tcp_forwarding: 'yes'
sftp_enabled: true
sftp_chroot: true

firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

timezone: Europe/Berlin

users:
  - name: lenni
    keys_url: https://github.com/leonardehrenfried.keys
  - name: hbruch
    keys_file: keys/hbruch.key

server_name: photon-eu.stadtnavi.eu
podman_prune_users:
  - root
tilemaker_create_extract: false
tilemaker_bounding_box: "-21.4,35.1,40.9,72.4"
tilemaker_check_referential_integrity: false

tileserver_domain: "{{ server_name }}"