---
collections:
- ansible.posix
- name: community.general
  version: 5.2.0
- name: community.docker
  version: 3.7.0

roles:
- src: geerlingguy.docker
  version: 4.1.0
- src: geerlingguy.certbot
  version: 4.2.0
- src: geerlingguy.swap
  version: 1.0.1
- src: geerlingguy.firewall
  version: 2.5.0
- src: dev-sec.ssh-hardening
  version: 9.7.0
