---
- name: Install packages
  apt:
    state: latest
    default_release: buster-backports
    name:
      - pyosmium
      - osm2pgsql
      - osmium-tool
      - curl

- name: Create data directory
  file:
    path: /var/poi/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Install config and script files
  template: src={{ item }} dest=/var/poi/
  with_items:
    - build-mbtiles
    - config-openmaptiles.json
    - process-openmaptiles.lua
    - germany-and-around.geojson
  notify: Restart poi

- name: Install systemd files
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - poi.service
  notify: Restart poi

