version: '3'

services:
  db:
    image: mariadb:10.9.3
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=matomo
      - MYSQL_DATABASE=matomo
      - MYSQL_PASSWORD={{ matomo_db_password }}
      - MYSQL_ROOT_PASSWORD={{ matomo_db_root_password }}
    env_file:
      - ./db.env
    ports:
      - 3306:3306

  app:
    image: matomo:{{ matomo_version }}-fpm-alpine
    restart: always
    links:
      - db
    volumes:
#      - ./config:/var/www/html/config:rw
#      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - {{ matomo_port }}:80

volumes:
  db:
  matomo:
