---
- name: Install base packages
  package:
    name:
      - python3-docker
    state: present

- name: Create photon network
  docker_network:
    name: photon-network

- name: Install systemd files for photon
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - photon-new.service

- name: Install systemd files for pelias-adapter
  template: src={{ item }} dest=/etc/systemd/system/
  with_items:
    - photon-pelias-adapter-new.service
  notify: Restart photon-pelias-adapter-new

- name: Set state of photon-new service
  systemd:
    state: stopped
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
  with_items:
    - photon-new.service

- name: Copy photon nginx site conf
  template:
    src: photon-new-site.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
  with_items:
    - "{{ photon_new_hostname }}"
  notify: Restart nginx